version: "3.7"

services:

  traefik:
    image: "traefik:v2.3"
    command:
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--ping.entryPoint=http"
      - "--providers.file.directory=/config"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost/ping"]
      interval: 30s
      timeout: 5ss
      retries: 3
      start_period: 10s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" #TODO: check if this needs
        # config volume from this repo as readonly
      - ./traefik/config:/config:ro
        # adding volume containing ssl certs
      - ./traefik/certs:/certs:ro
    networks:
      - gitlab-overlay
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  gitlab-master:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/-/readiness?all=1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m
    volumes:
      - ./gitlab/master/config:/etc/gitlab
    networks:
      gitlab-overlay:
        aliases:
          - 'gitlab.example.com'
    ports:
      - "22:22"
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab-master.rule=Host(`gitlab.example.com`)"
      - "traefik.http.routers.gitlab-master.tls=true"
      - "traefik.http.routers.gitlab-master.entrypoints=https"
      - "traefik.http.services.gitlab-master.loadbalancer.server.port=8000"

  gitlab-runner-host:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" #TODO: check if this needs
      - ./gitlab/runner/config:/etc/gitlab-runner
    networks:
      - gitlab-overlay

networks:
  gitlab-overlay: