version: "3.7"

services:

  traefik:
    image: "traefik:v2.3"
    command:
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.file.directory=/config"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
        # config volume from this repo as readonly
      - ./traefik/config:/config:ro
        # adding volume containing ssl certs
      - ./traefik/certs:/certs:ro
        # adding volume for log files
      - ./traefik/logs:/logs
    networks:
      - gitlab-overlay
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  gitlab-master:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.example.com'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/-/readiness?all=1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m
    ports:
      - 8000:80
    volumes:
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/config:/etc/gitlab
    networks:
      - gitlab-overlay
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab-master.rule=Host(`gitlab.example.com`)"
      - "traefik.http.routers.gitlab-master.tls=true"
      - "traefik.http.routers.gitlab-master.entrypoints=https"
      - "traefik.http.services.gitlab-master.loadbalancer.server.port=80"

  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine
  #   networks:
  #     - gitlab-overlay

networks:
  gitlab-overlay: